INSERT INTO PREFIX_megamenus_menu_lang VALUES("1","id_lang","Home","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("2","id_lang","Pages","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("4","id_lang","Blog","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("5","id_lang","Contact us","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("6","id_lang","Lookbook","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("7","id_lang","Sale","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("8","id_lang","Home 1","http://sw-themes.com/prestashop/granada/option1");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("9","id_lang","Home 2","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("10","id_lang","Home 3","http://sw-themes.com/prestashop/granada/option3");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("11","id_lang","Home 4","http://sw-themes.com/prestashop/granada/option4");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("12","id_lang","Home 5","http://sw-themes.com/prestashop/granada/option5");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("13","id_lang","Home 6","http://sw-themes.com/prestashop/granada/option6");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("14","id_lang","Fashion","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("15","id_lang","Funiture","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("16","id_lang","Electronics","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("17","id_lang","Gift","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("18","id_lang","Books","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("19","id_lang","Sport","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("20","id_lang","Games","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("30","id_lang","Blog","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("31","id_lang","Contact","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("33","id_lang","Features","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("34","id_lang","Copy Home 1","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("35","id_lang","Copy Home 2","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("36","id_lang","Copy Home 3","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("37","id_lang","Copy Home 4","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("38","id_lang","Copy Home 5","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("39","id_lang","Copy Home 6","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("40","id_lang","Shop","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("41","id_lang","CATEGORY","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("42","id_lang","CATEGORY LIST","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("43","id_lang","SLIDER BANNER","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("44","id_lang","PRODUCT","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("47","id_lang","Copy Copy Home 1","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("48","id_lang","Copy Copy Home 2","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("49","id_lang","Copy Copy Home 3","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("50","id_lang","Copy Copy Home 4","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("51","id_lang","Copy Copy Home 5","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("52","id_lang","Copy Copy Home 6","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("53","id_lang","SHOPPING CART","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("54","id_lang","CAMPARE PRODUCTS","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("55","id_lang","CHECKOUT","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("56","id_lang","Home 7","http://sw-themes.com/prestashop/granada/option7");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("57","id_lang","Right sidebar","http://sw-themes.com/prestashop/granada/option1/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("58","id_lang","Right Sidebar","http://sw-themes.com/prestashop/granada/option1/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("59","id_lang","Left Sidebar","http://sw-themes.com/prestashop/granada/option2/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("60","id_lang","Both Sidebars","http://sw-themes.com/prestashop/granada/option3/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("61","id_lang","Fullwidth","http://sw-themes.com/prestashop/granada/option5/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("62","id_lang","Post Page","http://sw-themes.com/prestashop/granada/option2/fr/smartblog/3_answer_to_your_question_about_prestashop_1_6.html");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("63","id_lang","Home 8","http://sw-themes.com/prestashop/granada/option7");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("64","id_lang","Home 9","http://sw-themes.com/prestashop/granada/option9");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("65","id_lang","Home 10","http://sw-themes.com/prestashop/granada/option10");
