INSERT INTO PREFIX_megaboxs_group_lang VALUES("1","id_lang","Top Rated","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("2","id_lang","From Twitter","","<ul class=\"twitter-top-widget\"><li> </li>\n</ul>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("3","id_lang","Top seller","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("4","id_lang","Information","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("5","id_lang","Powered by","","&lt;p class=&quot;copyright-text&quot;&gt;&amp;copy; 2014 Powered by WooCommerce&amp;trade;. All Rights Reserved.&lt;/p&gt;");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("6","id_lang","","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("7","id_lang","CUSTOMER SERVICE","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("8","id_lang","MY ACCOUNT","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("9","id_lang","FACEBOOK","","<div class=\"facebook-like-box\"><a class=\"facebook-like-btn\" href=\"#\">Like!</a>\n<p>1452 people like <a href=\"#\">Promokit</a></p>\n<div class=\"facebook-users clearfix\"><a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/anna.jpg\" alt=\"Anna\" width=\"50\" height=\"50\" />Anna</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/tom.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" />Tom</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/antuan.jpg\" alt=\"Antuan\" width=\"50\" height=\"50\" />Antuan</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/maria.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" />Maria</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/milla.jpg\" alt=\"Milla\" width=\"50\" height=\"50\" />Milla</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/justine.jpg\" alt=\"Justine\" width=\"50\" height=\"50\" />Justine</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/maria2.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" />Maria</a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option6/img/cms/tom2.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" />Tom</a></div>\n</div>");
