INSERT INTO PREFIX_megaboxs_group VALUES("1","1","0","1","1","widget padding-right-lg","product","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"6\",\"width\":\"12\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","4","1","1");
INSERT INTO PREFIX_megaboxs_group VALUES("2","1","0","1","1","widget padding-right-lg","twitter_feed","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"twitterFeed\":{\"username\":\"eternalfriend38\",\"query\":\"\",\"countItem\":\"2\",\"page\":\"1\",\"favorites\":0,\"avatar_size\":\"\",\"intro_text\":\"\",\"outro_text\":\"\"},\"flickrFeed\":{\"userids\":\"\",\"limit\":\"\",\"feedapi\":\"photos_public.gne\"},\"module\":{\"name\":\"\",\"hook\":\"\"}}","4","1","2");
INSERT INTO PREFIX_megaboxs_group VALUES("3","1","0","1","1","widget padding-right-lg","contact","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","4","1","3");
INSERT INTO PREFIX_megaboxs_group VALUES("4","2","0","2","1","col-sm-6 widget","link","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","3","1","1");
INSERT INTO PREFIX_megaboxs_group VALUES("5","3","0","3","1","","html","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","6","1","1");
INSERT INTO PREFIX_megaboxs_group VALUES("6","3","0","3","1","","module","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"blocksocial\",\"hook\":\"DisplayFooter\"}}","6","1","2");
INSERT INTO PREFIX_megaboxs_group VALUES("8","2","0","2","1","col-sm-6 widget","html","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"twitterFeed\":{\"username\":\"\",\"query\":\"\",\"countItem\":\"\",\"page\":\"\",\"favorites\":0,\"avatar_size\":\"\",\"intro_text\":\"\",\"outro_text\":\"\"},\"flickrFeed\":{\"userids\":\"\",\"limit\":\"\",\"feedapi\":\"photos_public.gne\"},\"module\":{\"name\":\"\",\"hook\":\"\"}}","3","1","4");
INSERT INTO PREFIX_megaboxs_group VALUES("9","2","0","2","1","col-sm-6 widget","link","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","3","1","2");
INSERT INTO PREFIX_megaboxs_group VALUES("10","2","0","2","1","col-sm-6 widget","link","{\"product\":{\"ids\":[],\"category\":\"2\",\"type\":\"auto\",\"orderBy\":\"position\",\"orderWay\":\"asc\",\"onCondition\":\"all\",\"onSale\":\"2\",\"onNew\":\"2\",\"onDiscount\":\"2\",\"maxCount\":\"3\",\"width\":\"4\",\"customWidth\":12},\"module\":{\"name\":\"\",\"hook\":\"\"}}","3","1","3");
