INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("1","id_lang","#","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442975593.jpg","Collection","<div class=\"banner-row-content collection-banner-content light text-center\"><h3 class=\"text-lowercase\">New men\'s</h3><h2 class=\"text-uppercase\">Collection</h2><h4 class=\"text-uppercase\">Choices Summer New</h4><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">SHOP NOW</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("3","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442976287.jpg","Arrivals","<div class=\"banner-row-content arrivals-banner-content left text-center\"><h3>New Shoes</h3><h2 class=\"text-uppercase\">Arrivals</h2><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">BUY IT NOW</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("4","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442979590.jpg","New Arrivals","<div class=\"banner-row-content new-arrivals-banner-content left text-center\"><h3 class=\"text-uppercase\">Our Spring / Summer</h3><h2 class=\"text-uppercase\">New Arrivals</h2><p>Donec gravida elit sed rhoncus eleifend. Nam viverra lacus non lobortis malesuada fusce.</p><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">SHOP NOW</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("5","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442979636.jpg","Facebook","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("6","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442979671.jpg","Banner Twitter","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("8","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442981385.jpg","Discount Codes & Offers","<div class=\"banner-row-content offers-banner-content light text-center\"><h3 class=\"text-uppercase\">Exclusive</h3><h2 class=\"text-uppercase\">Discount Codes & Offers</h2><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">SHOP NOW</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("9","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442981440.jpg","Dress Shirt","<div class=\"banner-row-content rated-banner-content text-center\"><h3>Top Rated</h3><h2 class=\"text-uppercase\">Dress Shirt</h2><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">Dress Shirt</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("10","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442981477.jpg","Mid Season Sale","<div class=\"banner-row-content season-banner-content light text-center\"><h3>14/07/14 - 14/08/14</h3><h2>Mid Season Sale</h2><p>Aliquam erat volutpat. Aliquam erat volutpat. Vestibulum ante ipsum faucibus orci luctus et ultrices posuere cubilia curae.</p><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">TAKE LOOK</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("11","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442982150.jpg","Suits & Coats","<div class=\"banner-row-content children-banner-content light text-center\"><h3>children</h3><h2>Suits & Coats</h2><p>Nulla dignissim felis, quis mollis quam elementum. Volutpat ultrices. Duis convallis consequat</p><a class=\"btn btn-custom-3 btn-lger min-width\" href=\"#\">LEARN MORE</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("12","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442982191.jpg","Banner Pinterest","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("13","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442992638.jpg","All About White","<div class=\"banner-row-content allabout-banner-content text-center\"><h3>All About</h3><h2 class=\"text-uppercase\">White</h2><a class=\"btn btn-custom-3 btn-lger min-width-md\" href=\"#\">SHOP NEW</a></div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("14","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442992995.jpg","","<div>{module}{\"mod\":\"blocknewsletter\", \"hook\":\"footer\"}{/module}</div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("15","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442994347.jpg","","<div>{module}{\"mod\":\"blocktestimonial\", \"hook\":\"displayHome\"}{/module}</div>");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("16","id_lang","","http://sw-themes.com/prestashop/granada/option8/modules/flexgroupbanners/images/1442994524.jpg","Banner Sale","");

