INSERT INTO PREFIX_megaboxs_group_lang VALUES("1","id_lang","Top Rated","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("2","id_lang","From Twitter","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("3","id_lang","Quick Contact","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("4","id_lang","Information","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("5","id_lang","Powered by","","<p class=\"copyright-text\">© 2014 Powered by WooCommerce™. All Rights Reserved.</p>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("6","id_lang","","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("8","id_lang","FACEBOOK","","<div class=\"facebook-like-box\"><a class=\"facebook-like-btn\" href=\"#\">Like!</a>\n<p>1452 people like <a href=\"#\">Promokit</a></p>\n<div class=\"facebook-users clearfix\"><a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/anna.jpg\" alt=\"Anna\" width=\"50\" height=\"50\" /><span>Anna</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/tom.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" /><span>Tom</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/antuan.jpg\" alt=\"Antuan\" width=\"50\" height=\"50\" /><span>Antuan</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/maria.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" /><span>Maria</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/milla.jpg\" alt=\"Milla\" width=\"50\" height=\"50\" /><span>Milla</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/justine.jpg\" alt=\"Justine\" width=\"50\" height=\"50\" /><span>Justine</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/maria2.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" /><span>Maria</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option1/img/cms/tom2.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" /><span>Tom</span></a></div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("9","id_lang","MY ACCOUNT","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("10","id_lang","CUSTOMER SERVICE","&lt;div class=&quot;sm-margin clearfix visible-sm&quot;&gt;&amp;nbsp;&lt;/div&gt;","");
