INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("1","id_lang","#","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442975593.jpg","Collection","New men\'sCollectionChoices Summer NewSHOP NOW");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("3","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442976287.jpg","Arrivals","New ShoesArrivalsBUY IT NOW");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("4","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442979590.jpg","New Arrivals","Our Spring / SummerNew ArrivalsDonec gravida elit sed rhoncus eleifend. Nam viverra lacus non lobortis malesuada fusce.SHOP NOW");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("5","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442979636.jpg","Facebook","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("6","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442979671.jpg","Banner Twitter","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("8","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442981385.jpg","Discount Codes & Offers","ExclusiveDiscount Codes & OffersSHOP NOW");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("9","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442981440.jpg","Dress Shirt","Top RatedDress ShirtDress Shirt");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("10","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442981477.jpg","Mid Season Sale","14/07/14 - 14/08/14Mid Season SaleAliquam erat volutpat. Aliquam erat volutpat. Vestibulum ante ipsum faucibus orci luctus et ultrices posuere cubilia curae.TAKE LOOK");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("11","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442982150.jpg","Suits & Coats","childrenSuits & CoatsNulla dignissim felis, quis mollis quam elementum. Volutpat ultrices. Duis convallis consequatLEARN MORE");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("12","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442982191.jpg","Banner Pinterest","");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("13","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442992638.jpg","All About White","All AboutWhiteSHOP NEW");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("14","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442992995.jpg","","{module}{\"mod\":\"blocknewsletter\", \"hook\":\"footer\"}{/module}");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("15","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442994347.jpg","","{module}{\"mod\":\"blocktestimonial\", \"hook\":\"displayHome\"}{/module}");
INSERT INTO PREFIX_flexgroupbanners_banner_lang VALUES("16","id_lang","","http://sw-themes.com/prestashop/granada/option10/modules/flexgroupbanners/images/1442994524.jpg","Banner Sale","");

