INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("1","id_lang","New Products","","","New Products","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("2","id_lang","Top Sellers","","","Top Sellers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("3","id_lang","Specials","#","","Specials","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("4","id_lang","Help & Contact","","","Help & Contact","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("5","id_lang","Shipping & Taxes","#","","Shipping & Taxes","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("6","id_lang","Return Policy","#","","Return Policy","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("7","id_lang","Suppliers","","","Suppliers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("8","id_lang","Orders History","","","Orders History","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("9","id_lang","Manufacturers","0","","Manufacturers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("10","id_lang","Our stores","#","","Our stores","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("11","id_lang","Size Guides","#","","Size Guides","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("12","id_lang","Carrers","#","","Carrers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("13","id_lang","Affiliates","#","","Affiliates","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("14","id_lang","Legal Notice","#","","Legal Notice","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("15","id_lang","Privacy & Security","#","","Privacy & Security","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("16","id_lang","Sitemap","#","","Sitemap","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("17","id_lang","My Account","","","My Account","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("18","id_lang","Personal information","#","","Personal information","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("19","id_lang","Addresses","#","","Addresses","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("20","id_lang","Discount","#","","Discount","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("21","id_lang","Orders history","#","","Orders history","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("22","id_lang","Your vouchers","#","","Your vouchers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("23","id_lang","Size Guides","#","","Size Guides","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("24","id_lang","Safe Shopping ","#","","Safe Shopping ","");
