INSERT INTO PREFIX_customcontent_item_lang VALUES("1","id_lang","DEVELOPMENT","","<p>Quisque ac quam id quam ullam. lorem corper dignissim ullamcorper ut nisi. Cras ullamcorper ullamcorper. Integer aliquam malesuada mi, eu interdum magna scelerisque eu.</p>","<div class=\"row\">","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("2","id_lang","MARKETING","","<p>Praesent gravida malesuada faucibus. Etiam vehicula massa eget nisl ante, posuere vel bibendum nisl elementum. Sed vel erat interdum, volutpat nisi imperdiet, mollis magna.</p>","","</div>");
INSERT INTO PREFIX_customcontent_item_lang VALUES("3","id_lang","DESIGN","","<p>Proin eget sodales magna. Proin ac est convallis,interdum odio vel, luctus nibh. Fusce iaculis sollicitudin metus sed. Vivamus quis pharetra, sviverra nibh ut, fermentum felis.</p>","<div class=\"row\">","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("4","id_lang","WEB HOSTING","","<p>Proin eget sodales magna. Proin ac est convallis, interdum odio vel, luctus nibh. Fusce iaculis sollicitudin metus sed. Cras vel augue eu augue fermentum sollicitudin et id nunc.</p>","","</div>");
INSERT INTO PREFIX_customcontent_item_lang VALUES("5","id_lang","Arron Rivera","","<h3>Walter Allen</h3><h4>Chief Executive Officer</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("6","id_lang","Courtney Bryant","","<h3>Courtney Bryant</h3><h4>SysAdmin</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("7","id_lang","Walter Allen","","<h3>Walter Allen</h3><h4>Chief Executive Officer</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("8","id_lang","Evan Brooks","","<h3>Evan Brooks</h3><h4>Project Manager</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("9","id_lang","Phoebe Bryant","","<h3>Phoebe Bryant</h3><h4>Singer</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");
INSERT INTO PREFIX_customcontent_item_lang VALUES("10","id_lang","Chandler Allen","","<h3>Chandler Allen</h3><h4>Unknown</h4><p>Phasellus iaculis enim et mauris augue euismod fermentum, at cursus augue bibendum. In vitae fringilla lorem. Proin bibendum magna ut ultrices.</p><ul class=\"social-links small clearfix\"><li><a href=\"#\" class=\"social-icon icon-facebook\" title=\"Facebook\"></a></li><li><a href=\"#\" class=\"social-icon icon-twitter\" title=\"Twitter\"></a></li><li><a href=\"#\" class=\"social-icon icon-dribbble\" title=\"Dribble\"></a></li><li><a href=\"#\" class=\"social-icon icon-email\" title=\"Email\"></a></li></ul>","","");

