INSERT INTO PREFIX_megamenus_menu VALUES("1","0","1","1","","","","PAG|index","","0","12","1","1");
INSERT INTO PREFIX_megamenus_menu VALUES("2","0","1","1","","","","PAG|module-smartblog-category","","0","12","1","2");
INSERT INTO PREFIX_megamenus_menu VALUES("4","0","1","1","","","","PAG|module-smartblog-category","","0","12","1","5");
INSERT INTO PREFIX_megamenus_menu VALUES("5","0","1","1","","","","PAG|contact","","0","12","1","6");
INSERT INTO PREFIX_megamenus_menu VALUES("6","0","1","1","","","","CUSTOMLINK|0","","0","12","0","7");
INSERT INTO PREFIX_megamenus_menu VALUES("7","0","1","1","","","","CUSTOMLINK|0","","0","12","0","8");
INSERT INTO PREFIX_megamenus_menu VALUES("8","1","1","1","","","","CUSTOMLINK|0","","0","0","1","1");
INSERT INTO PREFIX_megamenus_menu VALUES("9","1","1","1","","","","CUSTOMLINK|0","","0","0","1","8");
INSERT INTO PREFIX_megamenus_menu VALUES("10","1","1","1","","","","CUSTOMLINK|0","","0","0","1","9");
INSERT INTO PREFIX_megamenus_menu VALUES("11","1","1","1","","","","PAG|index","","0","0","1","10");
INSERT INTO PREFIX_megamenus_menu VALUES("12","1","1","1","","","","CUSTOMLINK|0","","0","0","1","11");
INSERT INTO PREFIX_megamenus_menu VALUES("13","1","1","1","","","","CUSTOMLINK|0","","0","0","1","12");
INSERT INTO PREFIX_megamenus_menu VALUES("14","0","2","1","http://sw-themes.com/prestashop/granada/option4/modules/megamenus/images/93ccc76e7c101899342f287d8409ea89_sidemenubg.png","category-icon icon-fashion","","PAG|index","","0","12","1","1");
INSERT INTO PREFIX_megamenus_menu VALUES("15","0","2","1","","category-icon icon-furniture","","PAG|index","","0","12","1","2");
INSERT INTO PREFIX_megamenus_menu VALUES("17","0","2","1","","category-icon icon-gifts","","CAT|3","","0","12","1","4");
INSERT INTO PREFIX_megamenus_menu VALUES("18","0","2","1","","category-icon icon-books","","CAT|3","","0","12","1","5");
INSERT INTO PREFIX_megamenus_menu VALUES("20","0","2","1","","category-icon icon-games","","CAT|3","","0","12","1","8");
INSERT INTO PREFIX_megamenus_menu VALUES("21","0","2","1","","category-icon icon-electronics","","CAT|3","","0","12","1","3");
INSERT INTO PREFIX_megamenus_menu VALUES("22","0","2","1","","category-icon icon-sport","","CAT|3","","0","12","1","7");
INSERT INTO PREFIX_megamenus_menu VALUES("23","1","1","1","","","","CUSTOMLINK|0","","0","0","1","13");
INSERT INTO PREFIX_megamenus_menu VALUES("24","0","1","1","","","","PAG|module-smartblog-category","","0","12","1","3");
INSERT INTO PREFIX_megamenus_menu VALUES("25","4","1","1","","","","CUSTOMLINK|0","","0","0","1","1");
INSERT INTO PREFIX_megamenus_menu VALUES("26","4","1","1","","","","CUSTOMLINK|0","","0","0","1","2");
INSERT INTO PREFIX_megamenus_menu VALUES("27","4","1","1","","","","CUSTOMLINK|0","","0","0","1","3");
INSERT INTO PREFIX_megamenus_menu VALUES("28","4","1","1","","","","CUSTOMLINK|0","","0","0","1","4");
INSERT INTO PREFIX_megamenus_menu VALUES("29","4","1","1","","","","CUSTOMLINK|0","","0","0","1","5");
INSERT INTO PREFIX_megamenus_menu VALUES("30","0","2","1","","category-icon icon-music","","CAT|3","","0","12","1","6");
INSERT INTO PREFIX_megamenus_menu VALUES("31","1","1","1","","","","CUSTOMLINK|0","","0","0","1","14");
INSERT INTO PREFIX_megamenus_menu VALUES("32","1","1","1","","","","CUSTOMLINK|0","","0","0","1","15");
INSERT INTO PREFIX_megamenus_menu VALUES("33","1","1","1","","","","CUSTOMLINK|0","","0","0","1","16");
