INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("1","id_lang","Category","","","Category","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("2","id_lang","Best sales","","","Best sales","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("3","id_lang","Cart","","","Cart","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("4","id_lang","Contact us","","","Contact us","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("5","id_lang","Discount","","","Discount","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("6","id_lang","Guest tracking","","","Guest tracking","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("7","id_lang","Order history","","","Order history","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("8","id_lang","Identity","","","Identity","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("9","id_lang","Manufacturers","","","Manufacturers","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("10","id_lang","Smart blog search","","","Smart blog search","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("11","id_lang","Smart blog tags","","","Smart blog tags","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("12","id_lang","New products","","","New products","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("13","id_lang","About us","#","","About us","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("14","id_lang","404","","","404","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("15","id_lang","Forget your password","","","Forget your password","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("16","id_lang","Prices drop","","","Prices drop","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("17","id_lang","Products comparison","","","Products comparison","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("18","id_lang","Sitemap","","","Sitemap","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("19","id_lang","Store","","","Store","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("20","id_lang","Suppliers","","","Suppliers","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("21","id_lang","Search","","","Search","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("22","id_lang","Forgot Your Password","","","Forgot Your Password","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("23","id_lang","My Account","","","My Account","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("24","id_lang","Address","","","Address","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("25","id_lang","banner","","http://sw-themes.com/prestashop/granada/option7/modules/megamenus/images/fd53064eb853181f3bba6b649566e5de_b186c9aea675bfd427f091c3a136d57d_megamenu-banner.jpg","banner","");
