INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("1","id_lang","Category","","","Category","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("2","id_lang","Best sales","","","Best sales","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("3","id_lang","Cart","","","Cart","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("4","id_lang","Contact us","","","Contact us","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("5","id_lang","Discount","","","Discount","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("6","id_lang","Guest tracking","","","Guest tracking","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("7","id_lang","Order history","","","Order history","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("8","id_lang","Identity","","","Identity","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("9","id_lang","Manufacturers","","","Manufacturers","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("10","id_lang","Smart blog search","","","Smart blog search","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("11","id_lang","Smart blog tags","","","Smart blog tags","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("12","id_lang","New products","","","New products","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("13","id_lang","About us","","","About us","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("14","id_lang","404","","","404","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("15","id_lang","Forget your password","","","Forget your password","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("16","id_lang","Prices drop","","","Prices drop","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("17","id_lang","Products comparison","","","Products comparison","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("18","id_lang","Sitemap","","","Sitemap","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("19","id_lang","Store","","","Store","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("20","id_lang","Suppliers","","","Suppliers","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("21","id_lang","Search","","","Search","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("22","id_lang","Forgot Your Password","","","Forgot Your Password","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("23","id_lang","My Account","","","My Account","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("24","id_lang","Address","","","Address","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("25","id_lang","Banner","","http://sw-themes.com/prestashop/granada/option9/modules/megamenus/images/f6360c767a49149e5df267ee7ca61e0b_megamenu-banner.jpg","Banner","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("119","id_lang","Multi-Layouts Options","#","","Multi-Layouts Options","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("143","id_lang","Banner","","http://sw-themes.com/prestashop/granada/option9/modules/megamenus/images/ab621394514139e540d6a6c2058003c9_banner2.jpg","Banner","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("144","id_lang","Powerful Admin Panel","#","","Powerful Admin Panel","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("145","id_lang","No Core Modifications","#","","No Core Modifications","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("146","id_lang","Fully Responsive","#","","Fully Responsive","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("147","id_lang","Multi ","#","","Multi ","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("148","id_lang","Multi ","#","","Multi ","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("149","id_lang","500+ Google Fonts","#","","500+ Google Fonts","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("150","id_lang","Advance Top Menu","#","","Advance Top Menu","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("151","id_lang","Advance Sidebars","#","","Advance Sidebars","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("152","id_lang","Sticky Menu","#","","Sticky Menu","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("153","id_lang","Advance Footer","#","","Advance Footer","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("154","id_lang","Parallax","#","","Parallax","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("155","id_lang","Ajax Loading","#","","Ajax Loading","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("156","id_lang","And Many Other Modules","#","","And Many Other Modules","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("157","id_lang","Vertical Mega Menu","#","","Vertical Mega Menu","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("158","id_lang","Parallax Testimonials","#","","Parallax Testimonials","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("159","id_lang","Parallax Newsletter","#","","Parallax Newsletter","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("160","id_lang","Parallax Fun Facts","#","","Parallax Fun Facts","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("161","id_lang","Shop The Look","#","","Shop The Look","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("162","id_lang","Smart Blog","#","","Smart Blog","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("163","id_lang","Animation","#","","Animation","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("164","id_lang","Media","#","","Media","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("165","id_lang","Tabs & Collapses","#","","Tabs & Collapses","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("166","id_lang","Top Rated Slider","#","","Top Rated Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("167","id_lang","Special Products Slider","#","","Special Products Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("168","id_lang","New Arrivals Slider","#","","New Arrivals Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("169","id_lang","Popular Products Slider","#","","Popular Products Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("170","id_lang","Brand Logos Slider","#","","Brand Logos Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("171","id_lang","Meet Our Team Slider","#","","Meet Our Team Slider","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("172","id_lang","Flexible Banners Module","#","","Flexible Banners Module","");
INSERT INTO PREFIX_megamenus_menuitem_lang VALUES("173","id_lang","And Many Many More...","#","","And Many Many More...","");
