INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("1","id_lang","New Products","","","New Products","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("2","id_lang","Top Sellers","","","Top Sellers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("3","id_lang","Specials","","","Specials","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("7","id_lang","Suppliers","","","Suppliers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("8","id_lang","Manufaturers","","","Manufaturers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("9","id_lang","Our Stores","","","Our Stores","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("16","id_lang","My Account","","","My Account","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("17","id_lang","Personal Infomation","#","","Personal Infomation","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("18","id_lang","Addresses","","","Addresses","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("19","id_lang","Discount","","","Discount","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("20","id_lang","Orders History","","","Orders History","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("21","id_lang","Your Vouchers","#","","Your Vouchers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("22","id_lang","Help & Contact","","","Help & Contact","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("23","id_lang","Shipping & Taxes","#","","Shipping & Taxes","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("24","id_lang","Return Policy","#","","Return Policy","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("25","id_lang","Carrers","#","","Carrers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("26","id_lang","Affiliates","#","","Affiliates","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("27","id_lang","Legal Notice","#","","Legal Notice","");
