INSERT INTO PREFIX_megamenus_menu_lang VALUES("1","id_lang","Home","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("2","id_lang","Pages","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("4","id_lang","Blog","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("5","id_lang","Contact us","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("6","id_lang","Lookbook","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("7","id_lang","Sale","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("8","id_lang","Home 1","http://sw-themes.com/prestashop/granada/option1");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("9","id_lang","Home 2","http://sw-themes.com/prestashop/granada/option2");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("10","id_lang","Home 3","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("11","id_lang","Home 4","http://sw-themes.com/prestashop/granada/option4");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("12","id_lang","Home 5","http://sw-themes.com/prestashop/granada/option5");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("13","id_lang","Home 6","http://sw-themes.com/prestashop/granada/option6");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("14","id_lang","Fashion","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("15","id_lang","Funiture","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("17","id_lang","Gift","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("18","id_lang","Books","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("20","id_lang","Games","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("21","id_lang","Electronics","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("22","id_lang","Sport & Tuourism","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("23","id_lang","Home 7","http://sw-themes.com/prestashop/granada/option7");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("24","id_lang","Features","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("25","id_lang","RIGHT SIDEBAR","http://sw-themes.com/prestashop/granada/option1/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("26","id_lang","LEFT SIDEBAR","http://sw-themes.com/prestashop/granada/option2/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("27","id_lang","BOTH SIDEBARS","http://sw-themes.com/prestashop/granada/option3/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("28","id_lang","FULLWIDTH BLOG","http://sw-themes.com/prestashop/granada/option5/en/module/smartblog/category");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("29","id_lang","POST PAGE","http://sw-themes.com/prestashop/granada/option3/en/smartblog/5_Vestibulum-ante-ipsum-primis-in-faucibus-orci.html");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("30","id_lang","Music","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("32","id_lang","Copy Home 1","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("33","id_lang","Copy Home 2","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("34","id_lang","Copy Home 3","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("35","id_lang","Copy Home 4","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("36","id_lang","Copy Home 5","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("37","id_lang","Copy Home 6","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("38","id_lang","Copy Home 7","");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("41","id_lang","Copy RIGHT SIDEBAR","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("42","id_lang","Copy LEFT SIDEBAR","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("43","id_lang","Copy BOTH SIDEBARS","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("44","id_lang","Copy FULLWIDTH BLOG","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("45","id_lang","Copy POST PAGE","#");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("46","id_lang","Home 8","http://sw-themes.com/prestashop/granada/option8");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("47","id_lang","Home 9","http://sw-themes.com/prestashop/granada/option9");
INSERT INTO PREFIX_megamenus_menu_lang VALUES("48","id_lang","Home 10","http://sw-themes.com/prestashop/granada/option10");
