INSERT INTO PREFIX_customhtml_module_lang VALUES("1","id_lang","Video","<div class=\"widget\"><h3>Latest Video</h3><div class=\"embed-responsive embed-responsive-4by3\"><iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/XGSy3_Czz8k\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe></div></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("2","id_lang","banner","<div class=\"xs-margin\"></div><div class=\"widget\"><div class=\"sidebar-banner\"><img class=\"img-responsive\" src=\"http://sw-themes.com/prestashop/granada/option2/img/cms/banner.jpg\" alt=\"banner\" height=\"320\" width=\"270\" /><div class=\"sidebar-banner-content\"><div class=\"vcenter-container\"><div class=\"vcenter\"><h5><span class=\"a\">New men</span>Collection</h5><a class=\"btn btn-custom-7 min-width-md\" href=\"#\">Buy it now</a></div></div></div></div></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("3","id_lang","Footer","<div><p class=\"copyright-text\">&copy; 2015 Powered by Kutethemes&#8482;. All Rights Reserved.</p>{module}{\"mod\":\"blocksocial\", \"hook\":\"displayFooter\"}{/module}</div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("4","id_lang","banner right on category page","<div class=\"xs-margin\"></div><div class=\"widget\"><div class=\"sidebar-banner\"><img class=\"img-responsive\" src=\"http://sw-themes.com/prestashop/granada/option2/img/cms/banner.jpg\" alt=\"banner\" height=\"320\" width=\"270\" /><div class=\"sidebar-banner-content\"><div class=\"vcenter-container\"><div class=\"vcenter\"><h5><span class=\"a\">New men</span>Collection</h5><a class=\"btn btn-custom-7 min-width-md\" href=\"#\">Buy it now</a></div></div></div></div></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("7","id_lang","flickr","<div class=\"widget\"><h3>Flickr Stream</h3><ul class=\"flickr-widget clearfix\"></ul></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("8","id_lang","bottom contact page","<div class=\"col-sm-7 padding-right-larger contact-box\"><h3>HOW TO CONTACT US</h3><p>Sed consequat, nibh ac imperdiet pharetra, tortor lectus tincidunt dolor, eget euismod diamsapien id mauris. Morbi aliquam venenatis odio in cursus. Integer mollis dui nec dui elementum, a faucibus tortor malesuada. Proin et imperdiet mi. Morbi odio erat, ultrices non lectus nec, tempor viverra nequtur.</p></div><div class=\"xs-margin visible-xs clearfix\"></div><div class=\"col-sm-5\"><div class=\"row\"><div class=\"col-md-7 contact-box\"><h3>Contact Details</h3><ul class=\"contact-list\"><li><span>Phone:</span>+430 980 1479</li><li><span>Email:</span>granada_shop@gmail.com</li><li><span>Skype:</span>granada_shop</li></ul></div><div class=\"xs-margin visible-xs clearfix\"></div><div class=\"col-md-5 contact-box\"><h3>Contact Info</h3><div class=\"contact-address\">United Kingdom<br />London 02587<br />Oxford Street 48/188</div></div></div></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("9","id_lang","Flicker Stream","<div class=\"widget\"><h3>Flickr Stream</h3><ul class=\"flickr-widget clearfix\"></ul></div>");
INSERT INTO PREFIX_customhtml_module_lang VALUES("10","id_lang","Video","<div class=\"widget\"><h3>Latest Video</h3><div class=\"embed-responsive embed-responsive-4by3\"><iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/XGSy3_Czz8k\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe></div></div>");

