INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("1","id_lang","My Account","","","My Account","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("2","id_lang","Personal Infomation","#","","Personal Infomation","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("3","id_lang","Addresses","","","Addresses","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("4","id_lang","Help & Contact","","","Help & Contact","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("5","id_lang","Shipping & Taxes","#","","Shipping & Taxes","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("6","id_lang","Return Policy","#","","Return Policy","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("7","id_lang","Discount","","","Discount","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("8","id_lang","Orders History","","","Orders History","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("9","id_lang","Your Vouchers","#","","Your Vouchers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("10","id_lang","Safe Shopping","#","","Safe Shopping","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("11","id_lang","Size Guides","","","Size Guides","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("12","id_lang","Carrers","#","","Carrers","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("13","id_lang","Affiliates","#","","Affiliates","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("14","id_lang","Legal Notice","#","","Legal Notice","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("15","id_lang","Privacy & Security","","","Privacy & Security","");
INSERT INTO PREFIX_megaboxs_menuitem_lang VALUES("16","id_lang","Sitemap","#","","Sitemap","");
