INSERT INTO PREFIX_megamenus_group_lang VALUES("1","id_lang","SHOP","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("2","id_lang","SHOP","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("3","id_lang","ABOUT","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("4","id_lang","EXTRA","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("5","id_lang","","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("6","id_lang","Clothing","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("7","id_lang","Shoes","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("8","id_lang","Accessories","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("13","id_lang","Computers","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("14","id_lang","Smart Phones","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("15","id_lang","Tablets","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("18","id_lang","Tours","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("19","id_lang","Climbing","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("20","id_lang","Ship Tours","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("21","id_lang","FEATURES","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("25","id_lang","","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("26","id_lang","FEATURES","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("27","id_lang","FEATURES","");
INSERT INTO PREFIX_megamenus_group_lang VALUES("28","id_lang","FEATURES","");
