INSERT INTO PREFIX_megaboxs_group_lang VALUES("1","id_lang","Free Delivery","","<div class=\"function-icon icon-truck\" style=\"background:none;border:1px solid #e61446;color:#e61446;\">Delivery</div>\n<div class=\"function-description\">\n<div class=\"function-title sub-title\" style=\"color:#64615c;font-size:20px;\">Free Delivery</div>\n<div class=\"function-desc-content\" style=\"color:#8d897f;\">Cras pellentesque, nisi ac tempus pellentesque, orci sem commodo urna, amet egestas ipsum orci sit amet.</div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("2","id_lang","customer service","","<div class=\"function-icon icon-phone\" style=\"background:none;border:1px solid #1694d6;color:#1694d6;\">Service</div>\n<div class=\"function-description\">\n<div class=\"function-title sub-title\" style=\"color:#64615c;font-size:20px;\">24/h customer service</div>\n<div class=\"function-desc-content\" style=\"color:#8d897f;\">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas praesent tempor.</div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("3","id_lang","payment secured","","<div class=\"function-icon icon-lock\" style=\"background:none;border:1px solid #cd42e9;color:#cd42e9;\">Payment</div>\n<div class=\"function-description\">\n<div class=\"function-title sub-title\" style=\"color:#64615c;font-size:20px;\">payment secured</div>\n<div class=\"function-desc-content\" style=\"color:#8d897f;\">Aenean porta adipiscing tortor, nec consequat nisi mollis sed. Aliquam orn are magna sed leo varius, quis.</div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("4","id_lang","Information","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("5","id_lang","Powered by","","<p class=\"copyright-text\">© 2014 Powered by WooCommerce™. All Rights Reserved.</p>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("6","id_lang","","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("7","id_lang","customer service","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("8","id_lang","FACEBOOK","","<div class=\"facebook-like-box\"><a class=\"facebook-like-btn\" href=\"#\">Like!</a>\n<p>1452 people like <a href=\"#\">Promokit</a></p>\n<div class=\"facebook-users clearfix\"><a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/anna.jpg\" alt=\"Anna\" width=\"50\" height=\"50\" /><span>Anna</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/tom.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" /><span>Tom</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/antuan.jpg\" alt=\"Antuan\" width=\"50\" height=\"50\" /><span>Antuan</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/maria.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" /><span>Maria</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/milla.jpg\" alt=\"Milla\" width=\"50\" height=\"50\" /><span>Milla</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/justine.jpg\" alt=\"Justine\" width=\"50\" height=\"50\" /><span>Justine</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/maria2.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" /><span>Maria</span></a> <a href=\"#\"><img src=\"http://sw-themes.com/prestashop/granada/option8/img/cms/tom2.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" /><span>Tom</span></a></div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("9","id_lang","My Account","","");
