INSERT INTO PREFIX_megaboxs_group_lang VALUES("1","id_lang","Top Rated","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("2","id_lang","From Twitter","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("3","id_lang","Quick Contact","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("4","id_lang","Information","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("5","id_lang","Powered by","","<p class=\"copyright-text\">© 2014 Powered by WooCommerce™. All Rights Reserved.</p>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("6","id_lang","","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("8","id_lang","FACEBOOK","","<div class=\"facebook-like-box\"><a class=\"facebook-like-btn\" href=\"#\">Like!</a>\n<p>1452 people like <a href=\"#\">Promokit</a></p>\n<div class=\"facebook-users clearfix\"><a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/anna.jpg\" alt=\"Anna\" width=\"50\" height=\"50\" />Anna</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/tom.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" />Tom</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/antuan.jpg\" alt=\"Antuan\" width=\"50\" height=\"50\" />Antuan</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/maria.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" />Maria</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/milla.jpg\" alt=\"Milla\" width=\"50\" height=\"50\" />Milla</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/justine.jpg\" alt=\"Justine\" width=\"50\" height=\"50\" />Justine</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/maria2.jpg\" alt=\"Maria\" width=\"50\" height=\"50\" />Maria</a> <a href=\"#\"><img src=\"http://dev03.ovicsoft.com/sonnc/granada/option4/img/cms/facebooks/tom2.jpg\" alt=\"Tom\" width=\"50\" height=\"50\" />Tom</a></div>\n</div>");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("9","id_lang","MY ACCOUNT","","");
INSERT INTO PREFIX_megaboxs_group_lang VALUES("10","id_lang","CUSTOMER SERVICE","&lt;div class=&quot;sm-margin clearfix visible-sm&quot;&gt;&amp;nbsp;&lt;/div&gt;","");
